/* Creating the database db_employees*/
CREATE DATABASE DB_EMPLOYEES;

/* Creating the table Employee. */
CREATE TABLE IF NOT EXISTS EMPLOYEE(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50),
  BIRTHDATE DATE,
  PHONE VARCHAR(50) NOT NULL,
  ADDRESS TEXT,
  EMAIL VARCHAR(50) NOT NULL,
  JOB VARCHAR(50) NOT NULL,
  SALARY NUMERIC NOT NULL,
  HIREDATE DATE,
  CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY(ID),
  CONSTRAINT UQ_EMPLOYEE_PHONE UNIQUE(PHONE),
  CONSTRAINT UQ_EMPLOYEE_EMAIL UNIQUE(EMAIL)
);

/* brought to you by: MichkaDaCoder */